version: '3.7'
services:
  database:
    image: kel2_database_1
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ~/wayshub-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'kel2'
      MYSQL_PASSWORD: 'Katasand2'
      MYSQL_DATABASE: 'wayshub'
  backend:
    depends_on:
      - database
    container_name: wayshub-be
    build: .
    stdin_open: true
    ports:
      - '5000:5000'
    expose:
      - '5000'
